#
# build image for nginx
# Static files will go into /usr/share/nginx/html
#

FROM nginx:1.19-alpine

ADD "nginx/nginx.conf" "/etc/nginx/nginx.conf"

RUN apk add --no-cache ca-certificates

CMD ["nginx", "-g", "daemon off;"]

# vim:syntax=Dockerfile
