version: '3.7'
services:

  swagger-ui:
    image: 'johnnywhoops/swagger-ui:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.swagger-ui

  web:
    image: 'johnnywhoops/web:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: 'no'
    depends_on:
      - 'redis'

  redis:
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  nginx: 
    image: 'johnnywhoops/nginx:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: 'no'
    depends_on:
      - 'web'
    env_file:
      - '.env'
    ports:
      - 80:80
      - 443:443

volumes:
  redis: {}
