#
# build gunicorn and flask app
# 1. setup.py packages src into a .whl file
# 2. pip intall setup.py in flask container
#

# build environment

FROM python:3.8-alpine3.11 AS builder

RUN apk add --no-cache \
    build-base=0.5-r1 \
    git

RUN addgroup -g 1000 -S python && \
    adduser -u 1000 -S python -G python

# set environment variables
ENV PYTHONUNBUFFERED=1

COPY ./src /code/src

COPY setup.py /code

COPY README.md /code

RUN chown -R python:python /code

WORKDIR /code

USER python

RUN python setup.py bdist_wheel

# production environment

FROM tiangolo/meinheld-gunicorn-flask:python3.8-alpine3.11

ENV APP_MODULE="web.myapp:app" \
    PATH="${PATH}:/app/bin" \
    GUNICORN_CMD_ARGS="--timeout 180"

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl", "-fs", "http://localhost/echo_request", "-o", "/dev/null" ]

RUN apk add --no-cache \
    curl \
    libffi \
    openssl

RUN rm -f /app/prestart.sh

RUN mkdir -p /app/job_logs

COPY --from=builder /code/dist/*.whl /packages/

ENV PYTHONPATH=.

# hadolint ignore=DL3013
RUN apk add --no-cache --virtual .build-deps \
    build-base \
    libffi-dev \
    openssl-dev \
    && pip install --upgrade --target /app /packages/*.whl \
    && rm -rf /root/.cache/pip/* \
    && apk --purge del .build-deps

