version: '3.7'
services:

  swagger-editor:
    image: 'johnnywhoops/swagger-editor:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.swagger-editor
    restart: 'no'
    volumes:
      - "./:/mnt"

  swagger-ui:
    image: 'johnnywhoops/swagger-ui:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.swagger-ui
    restart: 'no'
    volumes:
      - "./:/mnt"

  web:
    image: 'johnnywhoops/web:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: 'no'
    depends_on:
      - 'redis'
    environment:
      - BUILD_ENV=DEV
    command:
      gunicorn --bind="0.0.0.0:80" --workers 2 --timeout 30 --reload --log-level=debug --log-file=- "web.myapp:app"
    volumes:
      - ./src/web:/app/web


  redis:
    image: 'redis:6.0-alpine'
    restart: 'no'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  nginx: 
    image: 'johnnywhoops/nginx:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: 'no'
    depends_on:
      - 'web'
    env_file:
      - '.env'
    ports:
      - 80:80
      - 443:443

volumes:
  redis: {}
