version: '3.7'
services:

  swagger-ui:
    image: 'johnnywhoops/swagger-ui:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.swagger-ui
    ports:
      - "81:8080"
    volumes:
      - "./:/mnt"

  web:
    image: 'johnnywhoops/web:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: 'no' 
    ports:
      - "80:80"
    #volumes:
    #  - "./src/web:/app"

