version: '3.7'
services:

  swagger-ui:
    image: 'johnnywhoops/swagger-ui:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.swagger-ui
    ports:
      - "81:8080"
    volumes:
      - "./:/mnt"

  web:
    image: 'johnnywhoops/web:${TAG}'
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: 'no'
    depends_on:
      - 'redis'
    ports:
      - "80:80"
    command:
      gunicorn --bind="0.0.0.0:80" --workers 2 --timeout 30 --reload --log-level=debug --log-file=- "web.myapp:app"
    volumes:
      - ./src/web:/app/web


  redis:
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis: {}
